# {MSG} gets replaced by a message from below
# this means you dont need to repeat your prefix/suffix in each option in the list
Format: "&8[&6AFK&4+&8] {MSG}"
# Should each message be paired up with the same index in the other list
# e.g. if the second start message is chosen should the second stop message be chosen
Pairs: true

# List your start and stop messages in this list, if pairs is enabled make sure that the items line up in both lists
StartMessages:
  - "{PLAYER} is off on an adventure in the real world"
  - "I'm not sure that {PLAYER} is still around..."
  - "{PLAYER} is standing still"
  - "Just pretend that {PLAYER} isn't even here"
StopMessages:
  - "{PLAYER} survived the real world and has returned"
  - "Never mind, {PLAYER} is back"
  - "{PLAYER} stood still for {TIME}, kinda impressive"
  - "You can stop pretending, {PLAYER} came back"